In [2]:
import numpy as np

In [ ]:
a=[
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
]


5

In [4]:
[[i+1 for i in j] for j in a]

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

In [9]:
a = np.array(
[
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
]
)

In [6]:
a[1][1]

5

In [10]:
a[1, 1]

5

In [11]:
a[1: , 1:]

array([[5, 6],
       [8, 9]])

### Broadcasting


In [13]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [15]:
a*2.2

array([[ 2.2,  4.4,  6.6],
       [ 8.8, 11. , 13.2],
       [15.4, 17.6, 19.8]])

In [17]:
a.dtype

dtype('int32')

In [21]:
a+ np.array([1, 2, 3])

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [22]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [30]:
np.array([[1, 2, 3]]).T

array([[1],
       [2],
       [3]])

In [31]:
b = np.array(
[
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
]
)

In [35]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [37]:
a@b

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [36]:
np.dot(a, b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])